// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(grunt) {
    var description;
    description = 'Compile emblem templates into Handlebars.';
    return grunt.registerMultiTask('emblem', description, function() {
      var options;
      options = this.options({
        data: {}
      });
      return grunt.verbose.writeflags(options, 'Options');
    });
  };

}).call(this);
